/**
 * Todo Application Types
 * 
 * Type definitions for the todo feature including database schema types
 * and Supabase table definitions.
 */

/**
 * Todo item representing a task with completion status
 */
export interface Todo {
  id: string              // UUID v4 (generated by Supabase)
  user_id: string         // Foreign key to auth.users
  description: string     // Task description (1-500 chars)
  completed: boolean      // Completion status
  created_at: string      // ISO 8601 timestamp
  updated_at: string      // ISO 8601 timestamp
}

/**
 * Supabase table schema for todos
 * Defines the shape of data for insert, update, and select operations
 */
export interface TodoTable {
  Row: Todo
  Insert: Omit<Todo, 'id' | 'created_at' | 'updated_at'>
  // TODO: update_at should also be included - as it will eventually be overridden by the database trigger.
  Update: Partial<Omit<Todo, 'id' | 'user_id' | 'created_at'>>
}
